get:
  tags:
    - Subscriptions
    - Finance
  summary: Payment settings
  produces:
    - application/json
  parameters:
    - $ref: "#/parameters/authorization"
    - name: id
      in: path
      description: id of subscription to fetch the settings for
      required: true
      type: string
  responses:
    200:
      description: Returns payment settings
      schema:
        $ref: '#/definitions/PaymentSettings'
    403:
      description: unauthorized
      schema:
        $ref: '#/definitions/Status'
put:
  tags:
    - Subscriptions
    - Finance
  summary: Update payment settings
  description: "Set up automatic payment.  To disable automatic payment, pass an empty mandate_id."
  consumes:
    - application/json
  parameters:
    - $ref: "#/parameters/authorization"
    - name: id
      in: path
      description: id of subscription to update the settings for
      required: true
      type: string
    - name: settings
      in: body
      description: settings to use. To set no mandate, leave the mandate_id out.
      schema:
        $ref: '#/definitions/PaymentSettingsUpdate'
  responses:
    204:
      description: Payment settings updated
    403:
      description: unauthorized
      schema:
        $ref: '#/definitions/Status'
