type: object
title: Invoice settings
required:
  - billing_preference
properties:
  billing_preference:
    type: string
    enum:
      - paper
      - digital
  invoicing_address:
    $ref: '#/definitions/Address'
