type: object
title: Invoice settings
description: |
    If there is no contact information (invoicing_address) defined, no invoicing_address will be returned and
    the system will use the address of the customer.
required:
  - billing_preference
properties:
  billing_preference:
    type: string
    enum:
      - paper
      - digital
  invoicing_address:
    $ref: '#/definitions/ContactInformation'
