type: object
title: Update payment settings
required:
  - mandate_id
properties:
  mandate_id:
    description: |
      Id of the mandate to use for automatic payment.  Set it to an empty string to unset the mandate.
    type: string
  auto_topup:
    $ref: '#/definitions/AutoTopup'
